color_opts = [{'label':'plotly blue','value':'#1f77b4'},
              {'label':'plotly orange','value':'#ff7f0e'},
              {'label':'plotly green','value':'#2ca02c'},
              {'label':'plotly red','value':'#d62728'},
              {'label':'plotly purple','value':'#9467bd'},
              {'label':'plotly brown','value':'#8c564b'},
              {'label':'plotly pink','value':'#e377c2'},
              {'label':'plotly gray','value':'#7f7f7f'},
              {'label':'plotly yellow-green','value':'#bcbd22'},
              {'label':'plotly blue-teal','value':'#17becf'},
              {'label':'ing orange','value':'rgb(255,98,0)'},
              {'label':'ing lightgrey','value':'rgb(168,168,168)'},
              {'label':'ing indigo','value':'rgb(82,81,153)'},
              {'label':'ing sky','value':'rgb(296,166,218)'},
              {'label':'ing fuchsia','value':'rgb(171,0,102)'},
              {'label':'ing lime','value':'rgb(208,217,60)'},
              {'label':'ing leaf','value':'rgb(52,150,81)'},
              {'label':'ing mid grey','value':'rgb(118,118,118)'},
              {'label':'custom','value':'custom'}]

dash_opts = [{'label':'solid','value':'solid'},
             {'label':'dot','value':'dot'},
             {'label':'dash','value':'dash'},
             {'label':'longdash','value':'longdash'},
             {'label':'dashdot','value':'dashdot'},
             {'label':'longdashdot','value':'longdashdot'},
             {'label':'custom','value':'custom'}]

line_shape_opts = [{'label':'linear','value':'linear'},
                  {'label':'spline','value':'spline'},
                  {'label':'hv','value':'hv'},
                  {'label':'vh','value':'vh'},
                  {'label':'hvh','value':'hvh'},
                  {'label':'vhv','value':'vhv'}]

marker_symbol_opts=[{'label':'circle','value':0},
                    {'label':'square','value':1},
                    {'label':'diamond','value':2},
                    {'label':'cross','value':3},
                    {'label':'x','value':4},
                    {'label':'triangle-up','value':5},
                    {'label':'triangle-down','value':6},
                    {'label':'triangle-left','value':7},
                    {'label':'triangle-right','value':8},
                    {'label':'triangle-ne','value':9},
                    {'label':'triangle-se','value':10},
                    {'label':'triangle-sw','value':11},
                    {'label':'triangle-nw','value':12},
                    {'label':'pentagon','value':13},
                    {'label':'hexagon','value':14},
                    {'label':'hexagon2','value':15},
                    {'label':'octagon','value':16},
                    {'label':'star','value':17},
                    {'label':'hexagram','value':18},
                    {'label':'star-triangle-up','value':19},
                    {'label':'star-triangle-down','value':20},
                    {'label':'star-square','value':21},
                    {'label':'star-diamond','value':22},
                    {'label':'diamond-tall','value':23},
                    {'label':'diamond-wide','value':24},
                    {'label':'hourglass','value':25},
                    {'label':'bowtie','value':26},
                    {'label':'circle-cross','value':27},
                    {'label':'circle-x','value':28},
                    {'label':'square-cross','value':29},
                    {'label':'square-x','value':30},
                    {'label':'diamond-cross','value':31},
                    {'label':'diamond-x','value':32},
                    {'label':'cross-thin','value':33},
                    {'label':'x-thin','value':34},
                    {'label':'asterisk','value':35},
                    {'label':'hash','value':36},
                    {'label':'y-up','value':37},
                    {'label':'y-down','value':38},
                    {'label':'y-left','value':39},
                    {'label':'y-right','value':40},
                    {'label':'line-ew','value':41},
                    {'label':'line-ns','value':42},
                    {'label':'line-ne','value':43},
                    {'label':'line-nw','value':44}]


app = dash.Dash(__name__)
app.config['suppress_callback_exceptions']=True
app.layout = html.Div(className='row',
                     children=[html.Div(id='first-pane',
                                className='column-1',
                       children=[html.Button(id='create-graph-button',n_clicks=None,value=0),
                       html.Div(hidden=True,
                                id='graph-text-area-container',
                                children=[dcc.Input(id='graph-text-area',placeholder='enter graph name',type='text')]),
                       html.Div(id='graph-main-container',
                                hidden=True,
                                children=[dcc.Input(id='path-input-area',placeholder='enter path to pkl',type='text',disabled=True),
                                          html.Button('submit path',id='submit-path-button',disabled=True)]),
                       html.Div(id='graph-initials-container',
                                hidden=True,
                                children=[dcc.Input(id='graph-title',placeholder='enter graph title',type='text',),
                                                  dcc.Input(id='graph-width',placeholder='enter graph width',type='number',value=1200,required=True),
                                                  dcc.Input(id='graph-height',placeholder='enter graph height',type='number',value=600,required=True),
                                                  html.Button('add trace',id='add-trace-button'),
                                                  html.Div(id='traces-container')])
                       ]),
                       ## TITLE - WIDTH - HEIGHT AND TRACES ##
                       html.Div(id='body-container',
                                className='column-2',
                                n_clicks=0,
                                children=[
                                          html.Div(id='draw-graph-container',className='graph-itself')
                                ]),

                       ## TRACE PANE ##
                       html.Div(id='trace-pane',
                                className='column-3',
                       # DIVISION LEVEL 1 #
                                hidden=False,
                                children=[html.H3('TRACE PANEL'),
                                          html.Div(id='trace-pane-content',hidden=True,
                                            children=[dcc.Dropdown(id='trace-selector',options=[{'label':'trace-'+str(a), 'value':'trace-'+str(a)} for a in n_traces[1:]]),
                                          'visibility:',
                                          dcc.RadioItems(id='trace-visibility',
                                                        options=[{'label': 'visible', 'value': True},
                                                                 {'label': 'invisible', 'value': False},
                                                                 {'label': 'legend only', 'value': 'legendonly'},
                                                                 ],value=True), # NEW!! #
                                          'trace name:',
                                          dcc.Input(id='trace-name',placeholder='trace name',type='text'),
                                          'x axis:',
                                          dcc.Dropdown(id='trace-x-axis',options=[{'label':'primary horizontal', 'value':'x'},
                                                                                  {'label':'secondary horizontal', 'value':'x2'},
                                                                                  {'label':'third horizontal', 'value':'x3'},
                                                                                  {'label':'fourth horizontal', 'value':'x4'},]),
                                          'y axis:',
                                          dcc.Dropdown(id='trace-y-axis',options=[{'label':'primary vertical', 'value':'y'},
                                                                                  {'label':'secondary vertical', 'value':'y2'},
                                                                                  {'label':'third vertical', 'value':'y3'},
                                                                                  {'label':'fourth vertical', 'value':'y4'},]),
                                          'opacity:',
                                          dcc.Input(id='trace-opacity',placeholder='opacity',type='number',min=0,max=1),
                                          dcc.Checklist(id='trace-showlegend',options=[{'label':'show legend','value':True}],values=[True]),
                                          html.Div(id='trace-mode-container',
                                          # DIVISION LEVEL 2 - Applicable to Scatter Traces #
                                                   hidden=True,
                                                   children=[html.H4('[Line Properties]'),
                                                             html.Button('show',id='show-line-properties-button'),
                                                             html.Div(id='line-properties-pane',
                                                             # DIVISION LEVEL 3 #
                                                             children=[dcc.Checklist(id='trace-showlines',options=[{'label':'show lines','value':True}],values=[True]),
                                                                       'line width',
                                                                       dcc.Input(id='trace-line-width',type='number'),
                                                                       'line color',
                                                                       dcc.Dropdown(id='trace-line-color',options=color_opts),
                                                                       'line custom color:',
                                                                       dcc.Input(id='custom-line-color-input',placeholder='HEX CODE ONLY',type='text',disabled=True),
                                                                       'line dash type:',
                                                                       dcc.Dropdown(id='trace-line-dash',options=dash_opts),
                                                                       'line custom dash type:',
                                                                       dcc.Input(id='custom-line-dash-input',placeholder='SEPERATE NUMBERS WITH A COMMA',type='text',disabled=True),
                                                                       'line shape:',
                                                                       dcc.Dropdown(id='trace-line-shape',options=line_shape_opts),
                                                                       'line shape smoothing (0-1.3):',
                                                                       dcc.Input(id='trace-line-smoothing',type='number',disabled=True,min=0,max=1.3,value=1)]),

                                                             html.H4('[Marker Properties]'),
                                                             html.Button('show',id='show-marker-properties-button'),
                                                             html.Div(id='marker-properties-pane',
                                                             # DIVISION LEVEL 3 #
                                                             children=[dcc.Checklist(id='trace-showmarkers',options=[{'label':'show markers','value':True}],values=[True]),
                                                                       'marker size',
                                                                       dcc.Input(id='trace-marker-size',type='number'),
                                                                       'marker color',
                                                                       dcc.Dropdown(id='trace-marker-color',options=color_opts),
                                                                       'marker custom color:',
                                                                       dcc.Input(id='custom-marker-color-input',placeholder='HEX CODE ONLY',type='text',disabled=True),
                                                                       'marker symbol:',
                                                                       dcc.Dropdown(id='trace-marker-symbol',options=marker_symbol_opts),
                                                                       'marker symbol property:',
                                                                       dcc.RadioItems(id='trace-marker-symbol-property',
                                                                                      options=[{'label': 'solid', 'value': 0},
                                                                                               {'label': 'open', 'value': 100},
                                                                                               {'label': 'dot', 'value': 200},
                                                                                               {'label': 'open-dot', 'value': 300}],value=0),
                                                                       'marker border properties:',
                                                                       html.Button('show',id='show-marker-border-properties-button'),
                                                                       html.Div(id='marker-border-properties-pane',
                                                                       # DIVISION LEVEL 4 #
                                                                               children=[
                                                                               'marker border line width',
                                                                               dcc.Input(id='trace-marker-border-width',type='number'),
                                                                               'marker border line color',
                                                                               dcc.Dropdown(id='trace-marker-border-color',options=color_opts),
                                                                               'marker border line custom color:',
                                                                               dcc.Input(id='custom-marker-border-color-input',placeholder='HEX CODE ONLY',type='text',disabled=True),
                                                                               ])
                                                                        ]),
                                                             html.H4('[Text Properties]'),
                                                             dcc.Checklist(id='trace-showtext',options=[{'label':'show text','value':True}],values=[False])
                                                             ]),

                                          html.Div(id='bar-mode-container',
                                          # DIVISION LEVEL 2 - Applicable to Bar Traces #
                                                   hidden=True,
                                                   children=[html.H4('[Bar Properties]'),
                                                             html.Button('show',id='show-bar-general-properties-button'),
                                                             html.Div(id='bar-general-properties-pane',
                                                             # DIVISION LEVEL 3 #
                                                             children=['bar width',
                                                                       dcc.Input(id='trace-bar-width',type='number'),
                                                                       ]),
                                                             html.H4('[Marker Properties]'),
                                                             html.Button('show',id='show-bar-marker-properties-button'),
                                                             html.Div(id='bar-marker-properties-pane',
                                                             # DIVISION LEVEL 3 #
                                                             children=['bar marker color',
                                                                       dcc.Dropdown(id='trace-bar-marker-color',options=color_opts),
                                                                       'bar marker custom color:',
                                                                       dcc.Input(id='custom-bar-marker-color-input',placeholder='HEX CODE ONLY',type='text',disabled=True),
                                                                       'bar marker border properties:',
                                                                       html.Button('show',id='show-bar-marker-border-properties-button'),
                                                                       html.Div(id='bar-marker-border-properties-pane',
                                                                       # DIVISION LEVEL 4 #
                                                                               children=[
                                                                               'bar marker border line width',
                                                                               dcc.Input(id='trace-bar-marker-border-width',type='number'),
                                                                               'bar marker border line color',
                                                                               dcc.Dropdown(id='trace-bar-marker-border-color',options=color_opts),
                                                                               'bar marker border line custom color:',
                                                                               dcc.Input(id='custom-bar-marker-border-color-input',placeholder='HEX CODE ONLY',type='text',disabled=True)
                                                                               ])
                                                             ]),
                                        ])
                                    ])
                              ])
                      ])
