# update_graph
# UPDATE GRAPH START #
app.callback(output=Output('draw-graph-container', 'children'),
             inputs=[Input('graph-title','value'),
                     Input('graph-width','value'),
                     Input('graph-height','value'),
                     Input('body-container','trace-1'),
                     Input('body-container','trace-2'),
                     Input('body-container','trace-3'),
                     Input('body-container','trace-4'),
                     Input('body-container','trace-5'),
                     Input('body-container','trace-6'),
                     Input('body-container','trace-7'),
                     Input('body-container','trace-8'),
                     Input('body-container','trace-9'),
                     Input('body-container','trace-10'),
                     Input('trace-pane', 'dummy-name'),
                     Input('trace-pane', 'dummy-opacity'),
                     Input('trace-pane', 'dummy-showlegend'),
                     Input('trace-pane', 'dummy-showmode'),
                     Input('trace-pane', 'dummy-line-color'),
                     Input('trace-pane', 'dummy-line-dash'),
                     Input('trace-pane', 'dummy-line-shape'),
                     Input('trace-pane', 'dummy-line-width'),
                     Input('trace-pane', 'dummy-line-smoothing'),
                     Input('trace-pane', 'dummy-marker-size'),
                     Input('trace-pane', 'dummy-marker-color'),
                     Input('trace-pane', 'dummy-marker-symbol'),
                     Input('trace-pane', 'dummy-marker-border-color'),
                     Input('trace-pane', 'dummy-marker-border-width'),
                     Input('trace-pane', 'dummy-xaxis'),
                     Input('trace-pane', 'dummy-yaxis'),
                     Input('trace-pane', 'dummy-bar-marker-color'),
                     Input('trace-pane', 'dummy-bar-marker-border-width'),
                     Input('trace-pane', 'dummy-bar-marker-border-color'),
                     Input('trace-pane', 'dummy-bar-width'),
                     Input('trace-pane', 'dummy-visibility')
                     ])(update_graph)
# UPDATE GRAPH END

